x = int(input("x: 10"))
y = int(input("y: 20"))
print("두수의 합: 30", x+y)
print("두수의 차: -10", x-y)
print("두수의 곱: 200", x*y)
print("두수의 평균: 15", (x+y)/2)
print("큰수: "   , max(x, y))
print("작은수: ", min(x, y))